datapath: /home/ubuntu/NeRF_CT/data/nerf_synthetic/drums
savepath: /home/ubuntu/NeRF_CT/models/drums
exp_name: 50k_iters
lr_init: 0.0005
lr_final: 0.00005
pretrained_path: Null
Nf: 256
Nc: 64 # coarse and fine is not implemented yet
tn: 2
tf: 6
# Lp: 
# Ld: 0
tn_val: 2
tf_val: 6
num_iters: 100000
ckpt_model: 5000
ckpt_loss: 100
ckpt_images: 500
batch_size: 1024
render_batch: 8000
res_factor: 0.25 
decay_step: 100 
decay_rate: 0.1
val_idxs: [0,1]
num_train_imgs: -1 # -1 to use all images in the train set
train_with_phaseop: False


test_params:
  batch_size: 8000
  res_factor: 0.25
  loadpath: /home/ubuntu/NeRF_CT/models/drums/50k_iters/1669610402.0464501.pth
  datapath: /home/ubuntu/NeRF_CT/data/nerf_synthetic/drums
  savepath: /home/ubuntu/NeRF_CT/models/
  exp_name: drums_video
  im_set: test 
  im_idxs: 0 #[0,5,50,58,65] # renders rgb and depth for these indices from im_set
  animation: False # if True, only renders video 
  num_poses: 30
  theta: 30
  # Lp: 0
  # Ld: 0 
  Nf: 256
  Nc: 64 # coarse and fine is not implemented yet
  tn: 2
  tf: 6
  
